Edwards-Montgomery isomorphism proof
mit-plv/fiat-crypto pull request #1050
Opened 2021-11-15 15:31 UTC by talkon

Andres and I looked at the proof and it doesn't look simple to automate it fully.

2021-11-15 21:18 UTC, JasonGross requested changes
Please don't depend on autogenerated names in the proof scripts

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +Require Import UniquePose.
Minor preference for these being fully qualified.

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +    assert (f0 <> 0) by auto.
Please don't use autogenerated names, and instead use a `match` to pull these from the context.  Another possibility is asserting the implication early (something like `forall x, ??? -> x + 1 <> 0`) and specializing them later?

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +    assert (f <> 0). {
Again, please don't use autogenerated names

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +    assert (f0 <> 1) by fsatz.
Same comment about autogenerated names.

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +        | _ => progress Tactics.BreakMatch.break_match
No need to qualify these
```suggestion
        | _ => progress destruct_head' @M.point
        | _ => progress destruct_head' @prod
        | _ => progress destruct_head' @sum
        | _ => progress destruct_head' @and
        | _ => progress inversion_sum
        | _ => progress inversion_prod
        | _ => progress break_match_hyps
        | _ => progress break_match
```

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +        all: assert (f <> 0) by t2; assert (f0 <> 1) by fsatz; destruct H1; split; fsatz.
autogenerated names

2021-11-15 21:18 UTC, JasonGross commented on src/Curves/EdwardsMontgomery.v
> +        2-3, 5-6: t4.
Is there no way to determine what sort of thing you want to do based on the shape of the context?

2021-11-19 21:07 UTC, andres-erbsen commented
Jason and I discussed the challenges and potential benefits associated with further automating this file and didn't find clear directions beyond replacing autogenerated names with dumb matches for some feature of the context that contains these names. In the interest of lazyness (and keeping the file small), I suggested we punt doing that until we actually encounter an issue with the autogenerated names changing.

2021-11-19 21:07 UTC, merged