Adapt w.r.t. coq/coq#16004.
mit-plv/fiat-crypto pull request #1353
Opened 2022-08-05 17:16 UTC by ppedrot

This is 100% backwards compatible, but is lacking a submodule bump for bbv. The current commit of the latter is still incompatible with coq/coq#16004.

2022-08-05 17:20 UTC, ppedrot commented
This will need the same kind of CI tweaks as #1343. cc @JasonGross

2022-08-06 13:07 UTC, ppedrot commented
Not sure why this is failing, I don't understand the logs. They're basically diffs with the added locality attributes.

2022-08-06 14:14 UTC, JasonGross commented
This is failing because we check that the checked-in files are not modified by building, and I added a line at
https://github.com/mit-plv/fiat-crypto/blob/a0e7c050690f6f0611df8d1294a4e77921ea135d/.github/workflows/coq.yml#L59-L61
to remove the global attributes on old versions of Coq. I will fix this shortly.

2022-08-07 09:02 UTC, JasonGross requested changes
Please rebase on top of https://github.com/mit-plv/fiat-crypto/pull/1354 and https://github.com/mit-plv/fiat-crypto/pull/1355.  We don't need to drop support for versions earlier than 8.11.

2022-08-08 14:22 UTC, ppedrot commented
CI green. AFAIU this is ready.

2022-08-08 15:46 UTC, merged

2022-08-08 15:47 UTC, JasonGross commented
Merged