CLI stuff for dettman multiplication function
mit-plv/fiat-crypto pull request #1550
Opened 2022-12-22 22:02 UTC by OwenConoly

2022-12-23 07:18 UTC, JasonGross requested changes
Please amend the commits to remove the binary files, and add them to .gitignore

(This is a partial review, I'll look at the rest later)

2022-12-23 07:18 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
What is limb size?  Why do we need it here but not in unsaturated solinas?

2022-12-27 18:42 UTC, JasonGross commented on src/Arithmetic/Core.v
> + Lemma not_in_value_0 a d : ~ In d (map fst a) -> value_at_weight a d = 0.
```suggestion
  Lemma not_in_value_0 a d : ~ In d (map fst a) -> value_at_weight a d = 0.
```

2022-12-27 18:42 UTC, JasonGross commented on src/Arithmetic/Core.v
> + Lemma not_in_value_0 a d : ~ In d (map fst a) -> value_at_weight a d = 0.
Did you deliberately change the indentation?
```suggestion
  Lemma not_in_value_0 a d : ~ In d (map fst a) -> value_at_weight a d = 0.
```

2022-12-29 01:39 UTC, OwenConoly commented on src/Arithmetic/Core.v
> + Lemma not_in_value_0 a d : ~ In d (map fst a) -> value_at_weight a d = 0.
No, that was an accident

2022-12-29 02:52 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
Limb size is the thing referred to as "limbwidth" in the unsaturated solinas file.  I'll rename it into "limbwidth" in the dettman code.

The unsaturated solinas code just calculates the correct limbwidth as a function of the given prime and number of limbs, but the dettman code takes the limbwidth as a parameter.  I decided to do this because there is an easy generalization of the dettman algorithm to work with different limbwidths, and I don't know, in general, how to calculate the optimal limbwidth for the dettman algorithm (given a modulus and a number of limbs).

To calculate the limbwidth, the solinas code just divides the number of bits in the modulus by the number of limbs, but I don't know that that's always the right thing to do with the dettman algorithm.  The dettman algorithm takes advantage of the least significant limb having a significantly smaller size than the rest.  For example, with the bitcoin prime, we have four limbs with 52 bits, and then a last limb with 47 bits.  (That might not be quite right, but it's something like that.)  So for instance, if we wanted to implement the algorithm with 5 limbs and a modulus of size about 2^259, then having a limbwidth of 52 might work out poorly, and we might want it to be 53 instead--I'm not sure.

2023-01-03 13:27 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +    := (repeat (Some r[0 ~> 2 * input_magnitude * (2^limbwidth - 1)]%zrange) 4) ++ [Some r[0 ~> 2 * input_magnitude * (2^last_limb_width - 1)]%zrange].
Why 4?  Doesn't this hardcode things to 5 limbs?

2023-01-03 13:31 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
Wouldn't it be better then to take in last limb width as an argument (guaranteed to be a nat), and distribute the other bits evenly across the other limbs?  (And this would allow fractional bits, as we have in unsaturated solinas, too.)

2023-01-03 13:35 UTC, JasonGross commented on src/CLI.v
> +  Definition input_magnitude_spec : anon_argT
This sounds very similar to `inbounds_multiplier_spec`.  Is it different?  If not, please reuse `inbounds_multiplier_spec`

2023-01-03 13:46 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
> I don't know, in general, how to calculate the optimal limbwidth for the dettman algorithm

Is there a way to compute the valid range of bitwidths for the final limb?  E.g., is it always the case that you need exactly one extra bit of space in all the limbs but the last one, and you always need at least some minimum number of bits in the last limb?

2023-01-03 13:52 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
What's the reason for this change?  (And is it supposed to be in this PR, or another one?). It seems like it shouldn't change the generated code?

2023-01-03 13:54 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Oh, is `filter` not reifiable?

2023-01-03 13:57 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Should we just add support for reifying and rewriting `filter` by adding lines at
https://github.com/mit-plv/fiat-crypto/blob/6e6809be8290a7d7a9243b9491c09ec899ecb15b/src/Language/IdentifierParameters.v#L128
and
https://github.com/mit-plv/fiat-crypto/blob/6e6809be8290a7d7a9243b9491c09ec899ecb15b/src/Rewriter/Rules.v#L156-L163
?

2023-01-03 13:59 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
(I think I'd prefer the change that adds more reification support, since it builds inventory towards supporting more algorithms more easily.)

2023-01-08 19:49 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +    := (repeat (Some r[0 ~> 2 * input_magnitude * (2^limbwidth - 1)]%zrange) 4) ++ [Some r[0 ~> 2 * input_magnitude * (2^last_limb_width - 1)]%zrange].
Oops, I overlooked that.  I'll change it to (n -1), for both input_bounds and output_bounds.

2023-01-08 22:10 UTC, OwenConoly commented on src/CLI.v
> +  Definition input_magnitude_spec : anon_argT
It is slightly different, but `inbounds_multiplier_spec` is better - it's Q instead of nat, and it's a named argument instead of being anonymous.  I'll use `inbounds_multiplier_spec`.

2023-01-09 01:48 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Right, filter isn't reifiable.  I'll make it reifiable, and then revert the `value_at_weight` implementation.

2023-02-27 23:13 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
On second thought, I think I'll just change `value_at_weight` to use `partition` instead of `filter`.  Unless I was looking at things wrong, there would be some non-trivial work required to make `filter` reifiable.  In particular, I think I would need to write something analogous to the `interp_related_List_partition` lemma in [src/AbstractInterpretation/ZRangeProofs.v](https://github.com/mit-plv/fiat-crypto/blob/93f79b646576c767c58b54e5ec58957046aff490/src/AbstractInterpretation/ZRangeProofs.v#L139).

And I suppose we don't really need `filter` for anything.  It's easy enough, if slightly ugly, to replace it by `partition`.

2023-02-28 01:50 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
> Wouldn't it be better then to take in last limb width as an argument (guaranteed to be a nat), and distribute the other bits evenly across the other limbs? (And this would allow fractional bits, as we have in unsaturated solinas, too.)

I don't think that having fractional bits would be worth the effort.  I wrote Arithmetic/DettmanMultiplication.v with the assumption that the limbwidths weren't fractional.   I'm not completely sure how I would generalize certain things to account for fractional limbwidths.  And more importantly, I don't think that having fractional limbwidths (instead of just rounding up to the nearest integer) would allow for any significant tightening of the output bounds.  Certainly it would make calculating the output bounds more complicated.  I didn't actually calculate the output bounds myself, by the way---I copied them from [here](https://github.com/bitcoin-core/secp256k1/blob/0eb3000417fcf996e3805d0eb00f0f32b8849315/src/field_5x52_impl.h#L501).

And if we do keep the limbwidth non-fractional, then taking in the limbwidth of the first limbs as input (instead of the last limb) is a natural way to enforce that the limbwidth of the first limbs has to be a natural number.

2023-02-28 01:52 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
> > I don't know, in general, how to calculate the optimal limbwidth for the dettman algorithm
> 
> Is there a way to compute the valid range of bitwidths for the final limb? E.g., is it always the case that you need exactly one extra bit of space in all the limbs but the last one, and you always need at least some minimum number of bits in the last limb?

Maybe there is an easy way to do that?  I'm not sure.

2023-02-28 12:31 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
> In particular, I think I would need to write something analogous to the `interp_related_List_partition` lemma in [src/AbstractInterpretation/ZRangeProofs.v](https://github.com/mit-plv/fiat-crypto/blob/93f79b646576c767c58b54e5ec58957046aff490/src/AbstractInterpretation/ZRangeProofs.v#L139).

That's not necessary.  Just say that the bounds on the output of `filter` are `None` (`ZRange.ident.option.interp.None` or something?), which will make that proof trivial.

Roughly this means that bounds analysis won't work until filtering has been unfolded, but I think that's fine, and the pipeline hopefully shouldn't require any changes.

I believe the only lemma you need to prove is that `filter` is equal to some expression in terms of `list_rect`, to be used in the rewriting rules around
https://github.com/mit-plv/fiat-crypto/blob/93f79b646576c767c58b54e5ec58957046aff490/src/Rewriter/Rules.v#L144-L177

2023-02-28 12:33 UTC, JasonGross commented
Zig target failing with
```
src/main.zig:77:28: error: unable to load 'src/secp256k1_64.zig': FileNotFound
    try testVector(@import("secp256k1_64.zig"), expected);
```
Windows failing with
```
make: Nothing to be done for 'c-files'.
make: *** No rule to make target 'fiat-c/src/secp256k1_64.c', needed by 'lite-c-files'.  Stop.
```

2023-02-28 12:57 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
> I'm not completely sure how I would generalize certain things to account for fractional limbwidths.

I'm curious what breaks if you parameterize over an arbitrary weight function that satisfies
https://github.com/mit-plv/fiat-crypto/blob/93f79b646576c767c58b54e5ec58957046aff490/src/Arithmetic/Core.v#L1220-L1226.
(This shouldn't be considered to be blocking this PR though)

2023-02-28 18:29 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Oh, ok!  I didn't know I could do that.  I'll add reification support for filter, then.  I suppose the bounds on filter can be tightened later if necessary.

2023-02-28 18:41 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
Yeah, I could definitely parameterize over an arbitrary weight function, not change anything else, and the proof would still go through as before.  I was more wondering if there would be other things we'd want to modify if we want to allow for fractional bitwidths.

For instance, suppose we have a modular reduction from one position to another, but now (because the bitwidth is fractional) the number in the former position is too wide to fit (or bigger than we want) in the latter position, do we still want that reduction to be done as before?  Or should the algorithm be modified in some way?

Or should I just not worry about things like this, and just parameterize over the arbitrary weight function?  I'm not saying things will break if we allow for an arbitrary weight function, just that the algorithm might be somehow suboptimal.

2023-02-28 19:27 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
My intuition says "don't worry about this here, just parameterize over an arbitrary weight function".

Here's some slightly rambly explanation of my thinking:

AIUI, this is why unsaturated solinas needs to reduce multiple times / have a nontrivial carry chain?

I'm also lacking vision on the "most general form" of the algorithm, so a bit hesitant to make confident claims here, but my inclination is that if we do sometimes want a nonuniform weight, and the proof works fine with an arbitrary weight function, then we should parameterize the algorithm over an arbitrary weight function and leave it to the higher layers to specify the reasonable class of weight functions.  And if we find that we want to generalize the algorithm further, we can do that; I don't expect further generalizations to be hampered by parameterizing over the weight function.
Said another way, I don't expect further generalizations to overlap only partially with a generic weight function; I don't expect there to be an algorithmic generalization that can only be phrased at all if we don't generalize over the weight function.
(Example of further generalization: Like, right now auto bounds analysis takes care of ensuring bounds are tight enough everywhere, maybe at some point we'll prove that the current algorithm is sufficient boundswise for some class of weight functions, and this will inform what we expose on the CLI.)

FWIW, IIRC, the way we get bounds guesses for unsaturated solinas (in the Heuristics file) is by actually running the algorithm for the inputs that we think will saturate the bounds, skipping the carrying step, and then use that to determine how much we need to carry / how much headspace we have.  Maybe there's some similar algorithm here?

In any case, I'd be happy to see a change (either in this PR or in another one) that parameterizes the algorithm over a weight function, and then has the CLI take in whatever arguments are most fundamental / most aligned with the parameters we might want to fiddle with / most aligned with how you think about the algorithm.

2023-03-02 02:56 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
I've made this work, but I needed to make a change to src/Rewriter/Util/ListUtil.v in the rewriter submodule.

I don't really know how submodules work.  Should I make a separate pull request in the rewriter repository?  If so, can you give me permission to push to the rewriter repository?  Currently I get a 403 error.

2023-03-02 03:01 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
What change do you need to make to the rewriter?  (And are you sure it's necessary?) If you're adding a lemma to ListUtil, you should just add it to Fiat Crypto's copy.  In any case, yes, you should fork the rewriter project, and make a pull request.  Probably the easiest way to do this is to clone it from scratch and copy the change you made in the submodule to the fresh clone of the rewriter, and push it to your fork.  (You can also do this directly in the submodule with `git remote add `)

2023-03-02 04:46 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Yeah, I'm just adding a couple lemmas to ListUtil.  The lemmas prove that filter is "Proper".  I don't know what that means, but it seems to be kinda related to functional extensionality.  And I think the lemmas are necessary, because building was failing without them.

2023-03-02 05:40 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Here's the error message that happens when I try to build without the ListUtil lemmas:

WARNING: Could not automatically prove Proper lemma
(Morphisms.Proper
   (Morphisms.respectful (Morphisms.respectful eq eq)
      (Morphisms.respectful eq eq))
   (List.filter (A:=Compilers.base.interp base_interp t)))
  Please ensure this goal can be solved by typeclasses eauto
File "./src/Language/IdentifiersBasicGENERATED.v", line 18, characters 9-28:
Error: Cannot infer an existential variable of type
"Morphisms.Proper
   (Morphisms.respectful (Morphisms.respectful eq eq)
      (Morphisms.respectful eq eq))
   (List.filter (A:=Compilers.base.interp base_interp t))" (no type class
instance found) in environment:
t : Compilers.base.type base

2023-03-02 05:54 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Yeah, you should just add `Instance Proper_filter_eq {A} : Proper ((eq ==> eq) ==> eq ==> eq) (@filter A)` with a proof to to https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ListUtil/Filter.v, and add a `Require Import` in `IdentifiersBasicGENERATED.v`.  (Add `Require Import Coq.Classes.Morphisms.` if the notation fails to parse; you may also need `Coq.Relations.Relations`, `Coq.Classes.RelationClasses`, and/or `Coq.Setoids.Setoid`; I can never remember which of these is required for which things.)

To explain `Proper`: `Proper (Morphisms.respectful P Q) f` (generally written `Proper (P ==> Q) f`) means "if the inputs of `f` are related by `P`, then the outputs are related by `Q`".  Technically, `Proper R x` is just defined as `R x x`, and `respectful P Q f g` is `forall x y, P x y -> Q (f x) (g y)`.

2023-03-02 05:58 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
Ok, so I should delete this pull request: https://github.com/mit-plv/rewriter/pull/99?

2023-03-02 05:58 UTC, JasonGross commented on src/AbstractInterpretation/ZRangeProofs.v
> +          Qed.
I see you went for the fancier bounds analysis? :-)

2023-03-02 05:58 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
And just make the change in https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ListUtil/Filter.v instead?

2023-03-02 05:58 UTC, JasonGross commented on src/Arithmetic/Core.v
> +      + rewrite Associational.eval_cons. rewrite <- IHa'. apply Z.eqb_eq in E. rewrite E. simpl. lia.
These changes can be reverted now, right?

2023-03-02 05:59 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    - cbv [value_at_weight]. simpl. destruct (d =? fst x) eqn:E.
This can also be reverted?

2023-03-02 05:59 UTC, JasonGross commented on src/Arithmetic/Core.v
And this can also be reverted, right?

2023-03-02 06:04 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    fold_right (fun p sum => if (d =? fst p) then (sum + snd p) else sum) 0 a.
> Ok, so I should delete this pull request: [mit-plv/rewriter#99](https://github.com/mit-plv/rewriter/pull/99)?
> And just make the change in https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ListUtil/Filter.v instead?

Yes, please

2023-03-02 06:13 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +      + rewrite Associational.eval_cons. rewrite <- IHa'. apply Z.eqb_eq in E. rewrite E. simpl. lia.
Yes!

2023-03-02 18:30 UTC, OwenConoly commented on src/Arithmetic/Core.v
> +      + rewrite Associational.eval_cons. rewrite <- IHa'. apply Z.eqb_eq in E. rewrite E. simpl. lia.
This pull request now does not include any changes to Core.v

2023-03-02 18:32 UTC, OwenConoly commented on src/AbstractInterpretation/ZRangeProofs.v
> +          Qed.
Yes!  That was fun.

2023-03-02 18:44 UTC, JasonGross commented on src/Language/IdentifiersBasicGENERATED.v
> +Require Import Util.ListUtil.Filter.
Minor:
```suggestion
Require Import Crypto.Util.ListUtil.Filter.
```

2023-03-02 18:50 UTC, JasonGross commented on src/Util/ListUtil/Filter.v
> +  Lemma filter_Proper {A} : Proper (pointwise_relation _ eq ==> eq ==> eq) (@List.filter A).
Minor: I don't see any reason to not make this an instance too, as it'll allow a bit more setoid rewriting 
```suggestion
  #[export] Instance filter_Proper {A} : Proper (pointwise_relation _ eq ==> eq ==> eq) (@List.filter A).
```

2023-03-02 19:23 UTC, JasonGross approved these changes
Looking good!  I'm happy to have this merged once it's rebased and the CI builds fine.

2023-03-02 19:23 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +  Definition output_magnitude_last_limb : Q := input_magnitude / 2 + 1 / 4. (* Where these bounds came from: https://github.com/bitcoin-core/secp256k1/blob/0eb3000417fcf996e3805d0eb00f0f32b8849315/sr
Plausibly this should be moved to a Heuristics file (a la UnsaturatedSolinasHeuristics), though it's fine to leave that for later.

2023-03-03 22:21 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
I'm trying to do this now, and I've gotten stuck right here: https://github.com/mit-plv/fiat-crypto/blob/3322f772f999f0941b5e1633fe433bfaa4ba957d/src/PushButtonSynthesis/DettmanMultiplication.v#L183-L190

Coq complains about the last argument on line 188.  The issue is that `reified_mul_gen` wants a weight function as input---the type should be whatever the "reified equivalent" of `nat -> Z` is.  I don't know how to reify a function.  Can I do this, or do I need to refactor things somehow?

If the answer is that I need to refactor things, I was thinking of changing the following line to take a couple of integers (a numerator and denominator) as parameters, instead of a function.
https://github.com/mit-plv/fiat-crypto/blob/3322f772f999f0941b5e1633fe433bfaa4ba957d/src/Arithmetic/DettmanMultiplication.v#L18

2023-03-05 16:27 UTC, JasonGross commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
> If the answer is that I need to refactor things, I was thinking of changing the following line to take a couple of integers (a numerator and denominator) as parameters, instead of a function.

Yes, that's the solution we use at https://github.com/mit-plv/fiat-crypto/blob/990bf2c3fccc13b747647834f3c7b853fa1da09d/src/Arithmetic/ModOps.v#L16-L19 and https://github.com/mit-plv/fiat-crypto/blob/990bf2c3fccc13b747647834f3c7b853fa1da09d/src/Arithmetic/Freeze.v#L143-L146

I'd suggest adding a `mod_ops` section at the bottom like we do for `Freeze`, defining a version that is specified to the numerator, denominator pair, and then reify that.

2023-03-05 17:23 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
Ah, ok.  I like the idea of keeping the algorithm in terms of the weight function and it’s hypotheses, so adding in the section at the bottom seems like a very nice solution.

2023-03-06 15:18 UTC, andres-erbsen commented
I like the direction this is going. We also should make sure we can put together an artifact tomorrow, even if that means merging a version we intend to improve later. Where do you think we currently stand wrt that?

2023-03-07 01:20 UTC, OwenConoly commented
> I like the direction this is going. We also should make sure we can put together an artifact tomorrow, even if that means merging a version we intend to improve later. Where do you think we currently stand wrt that?

I think it'll be in a mergeable state in a couple hours!

2023-03-07 02:38 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +  Definition output_magnitude_last_limb : Q := input_magnitude / 2 + 1 / 4. (* Where these bounds came from: https://github.com/bitcoin-core/secp256k1/blob/0eb3000417fcf996e3805d0eb00f0f32b8849315/sr
I think I'll leave that for later.

2023-03-07 03:41 UTC, OwenConoly commented on src/PushButtonSynthesis/DettmanMultiplication.v
> +          (limb_size : nat)
Ok, I think I've made the fractional bitwidths work properly.  Thanks for the helpful thoughts!

2023-03-07 05:57 UTC, JasonGross requested changes
Zig still fails, you need to update https://github.com/mit-plv/fiat-crypto/blob/990bf2c3fccc13b747647834f3c7b853fa1da09d/fiat-zig/src/main.zig#L75 with the rename (and ideally add a test for dettmann)

2023-03-07 06:31 UTC, OwenConoly commented
I fixed the zig thing!  I didn't add a dettman test, mostly because I don't understand much of what is going on in the main.zig file.  Perhaps Andres can help me figure that out at some point---and I should probably add tests for the other languages sometime, too.

2023-03-07 13:06 UTC, merged