Inversion (WIP)
mit-plv/fiat-crypto pull request #670
Opened 2020-03-06 14:18 UTC by bshvass

The following PR is an attempt at implementing a constant time inversion algorithm by D.J Bernstein (available at https://gcd.cr.yp.to/papers.html#safegcd).
At the moment it is just a subroutine, called divstep2 in the paper, which is implemented and proven functionally correct. This is the content of src/Arithmetic/Inv.v. It can be printed to C by the code in src/PushButtonSynthesis/TestInv.

Since it is only a subroutine, there is a C implementation of the remaining steps in test-inversion-c/test_bls.c (this is the inversion function; the main is a test).
An implementation using the divstep2 as generated by Fiat is also available in the RELIC toolkit (https://github.com/relic-toolkit/relic see commit bd87b62e0acb1d65b360d104059d29ebd676cd97)
This achieves quite a good performance (about twice as slow as hand optimized, non-constant time extended euclidean) and there are still many optimizations which can be done.

To be able to generate the full algorithm, however, we need bounded loops and/or function calls to be supported. 
Also one optimization (which is the implementation presented in the Bernstein paper) requires multiplication of 64-bit numbers and saturated multi limbs numbers (e.g. 128-bit, 192-bit etc. (NOT mod p)). Is this something that is already supported? I was able to find a sat_mul function, but not one which was reifiable (in src/Arithmetic/Saturated.v).

2020-03-09 18:00 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma opp_mod2 a : a mod 2 = - a mod 2.
Belongs in `src/Util/ZUtil/Modulo.v`

2020-03-09 18:02 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +  f (select cond a b) = Z.zselect cond (f a) (f b).
I think this belongs in `Section select` in `src/Arithmetic/Core.v`.  @jadephilipoom do you agree?

2020-03-09 18:03 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma land_pow2 a b :
This belongs in `src/Util/ZUtil/Land.v`, I believe

2020-03-09 18:03 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma testbit_small_neg a b
Belongs in `src/Util/ZUtil/Testbit.v`

2020-03-09 18:03 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma land_pow2_small a b
Belongs in `src/Util/ZUtil/Land.v`

2020-03-09 18:03 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma land_pow2_small_neg a b
Belongs in `src/Util/ZUtil/Land.v`

2020-03-09 18:03 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma lor_add a b (Hand : a &' b = 0) : a ||' b = a + b.
Belongs in `src/Util/ZUtil/Lor.v`

2020-03-09 18:04 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma lor_small_neg a b
Belongs in `src/Util/ZUtil/Lor.v`

2020-03-09 18:04 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma testbit_large a b
Belongs in `src/Util/ZUtil/Testbit.v`

2020-03-09 18:04 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma land_div2 a b (Ha : 0 <= a < 2^(b + 1))  :
Belongs in `src/Util/ZUtil/Land.v`

2020-03-09 18:10 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +    rewrite <- Z.pow_add_r, Zplus_minus; lia. Qed.
I think you are looking for `Z.testbit_add_shiftl_high` in `src/Util/ZUtil/Shift.v`.  But please instead add a version of this combined lemma using `Z.shiftl` instead of `Z.add` to `src/Util/ZUtil/Shift.v`, and then the only thing you have to do here is convert `2^b * c` to `c << b` and then you can just apply that lemma.

2020-03-09 18:11 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +                              else Z.testbit c (n - b).
Hmm, is there a reason to have this combined lemma rather than converting `2^b * c` to `c << b` at the use site?  (The latter is easier on file organization.)

2020-03-09 18:12 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma arshift_small m a
Please move `arshift` to `ZUtil.Definitions.arithmetic_shiftr` and move this to a new file ``src/Util/ZUtil/ArithmeticShiftr.v`

2020-03-09 18:12 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma arshift_large m a
idem

2020-03-09 18:12 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Lemma arshift_spec m a
idem

2020-03-09 18:13 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +  intros. inversion H; subst. reflexivity. inversion H0. subst.
Please don't use autogenerated names.  Also consider using the `distr_length` tactic and/or `autorewrite with distr_length`, and add lemmas like this to the `distr_length` hint database.  (I might be naming it wrong; there might not be an underscore.)

2020-03-09 18:14 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +(* Lemma length_sat_zero machine_wordsize n : *)
Why is this commented out?

2020-03-09 18:15 UTC, JasonGross commented on src/Arithmetic/JumpDivstep.v
> +Require Import Inv.
```suggestion
Require Import Crypto.Arithmetic.Inv.
```

2020-03-09 18:15 UTC, JasonGross commented on src/Arithmetic/JumpDivstep.v
> +Require Import Lia.
```suggestion
Require Import Coq.micromega.Lia.
```

2020-03-09 18:15 UTC, JasonGross commented on src/Arithmetic/JumpDivstep.v
> +Open Scope Z.
```suggestion
Local Open Scope Z_scope.
```

2020-03-09 18:16 UTC, JasonGross commented on src/PushButtonSynthesis/TestInv.v
> +  [3608227726454314319; 13347543502301691909; 6296135691958860625; 10026531341796875211; 7850492651313966083; 1291314412115845772].
Why write this out?

2020-03-09 18:17 UTC, JasonGross commented on src/PushButtonSynthesis/TestInv.v
> +Print saturated_bounds_list.
Is this leftover cruft?

2020-03-09 19:31 UTC, jadephilipoom commented on src/Arithmetic/Inv.v
> +Definition sat_rshift machine_wordsize n f :=
I'd call this something like `sat_shiftr1`, to make it clear you're only shifting by one bit.

2020-03-09 20:02 UTC, JasonGross commented on test-inversion-c/bls12_381_q_64.c
> +  f
I don't see any literals... @andres-erbsen what are you expecting?

2020-03-09 20:04 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Definition arshift (m a : Z) :=
If so, they should get better names, I think.

2020-03-09 20:06 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Definition arshift (m a : Z) :=
If so, they should get longer names, I think.  It was not clear to me that `twosc` was "twos complement" until just now (I thought it had something to do with the `s-c` encoding we use for primes...)

2020-03-09 20:10 UTC, JasonGross commented
The standard way that things here fail to reify is that we don't support `Q`, and some of the weight stuff uses `Q`, iirc.  We could just add support for `Q`, that might make things nicer rather than having to give the numerator and denominator separately.

2020-03-11 05:09 UTC, JasonGross commented
> I also can't think of a reason why the operations at https://github.com/mit-plv/fiat-crypto/blob/master/src/Arithmetic/Saturated.v#L798 shouldn't be reifiable -- but perhaps I am missing something here? What happened when you tried to reify it?

The issue is not in fact `Q` (though I made a branch that adds support for reifying `Q` [here](https://github.com/JasonGross/fiat-crypto/tree/support-Q), but idk if it's worth merging, since we don't actually use `Q` anymore.  Thoughts?)
In fact, all of these operations do work fine, as evidenced by adding the following succeeding lines to `CompilersTestCases.v`:
```coq
Require Import Arithmetic.Saturated.
Import Saturated.Rows.
Notation Reify v := (ltac:(let x := Reify v in exact x)) (only parsing).
Definition radd := Reify add.
Definition rsub := Reify sub.
Definition rconditional_add := Reify conditional_add.
Definition rconditional_sub := Reify conditional_sub.
Definition rsub_then_maybe_add := Reify sub_then_maybe_add.
Definition rmul := Reify mul.
Definition radjust_s := Reify adjust_s.
Definition rsat_reduce := Reify sat_reduce.
Definition rrepeat_sat_reduce := Reify repeat_sat_reduce.
Definition rmulmod := Reify mulmod.
Definition rdivmod := Reify divmod.
```

2020-03-12 12:05 UTC, bshvass commented on src/Arithmetic/Inv.v
> +Infix "||'" := Z.lor (at level 50) : Z_scope .
Good point. Note that the `|` in `Util/Notations.v` is the unicode character `∣` (0x2223), which confused me. I just changed this.

2020-03-12 12:08 UTC, bshvass commented on src/Arithmetic/Inv.v
> +    rewrite <- Z.pow_add_r, Zplus_minus; lia. Qed.
Thanks for point me to `Shift.v`! This lemma was already there (`Z.testbit_add_shiftl_full`).

2020-03-12 19:37 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Infix "||'" := Z.lor (at level 50) : Z_scope .
Oh, wow, I did not realize this.  I think we may want to just delete `Reserved Infix "∣" (at level 50).` because otherwise it may conflict with various Ltac notations as well as the notations for inductives and `match`, but changing `∣'` to `|'` should be fine, and I support this.

2020-05-21 14:36 UTC, huitseeker commented
Hey @bshvass, let me know if can help out with this or if you mind me just jumping in?

2020-05-25 16:46 UTC, JasonGross commented on inversion-c/test-inversion.c
> +  srand(time(0));
If we're going to be running tests, please write the seed to stdout, and allow passing the seed as a command-line argument, so that if it fails, we can reproduce the failing behavior.

2020-05-25 16:48 UTC, JasonGross commented on inversion-c/test-inversion.c
> +      	return 1;
Please use spaces rather than tabs
```suggestion
        printf("FAIL\n");
        return 1;
```

2020-05-25 16:49 UTC, JasonGross commented on src/Arithmetic/Core.v
> +    Proof. unfold select, Z.zselect.
```suggestion
    Proof using Type. unfold select, Z.zselect.
```
(Assuming this is the correct set of assumptions)

2020-05-25 16:49 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +(* An implementation of the divsteps2 algorithm from "Fast constant-time gcd computation and modular inversion."
Nit for better coqdocing
```suggestion
(** An implementation of the divsteps2 algorithm from "Fast constant-time gcd computation and modular inversion." 
```

2020-05-25 16:50 UTC, JasonGross commented on src/Arithmetic/Inv.v
> +Definition sat_add machine_wordsize n f g :=
Alternatively,
```suggestion
Local Definition sat_add machine_wordsize n f g :=
```
will cause the unqualified name to not be available even after `Import`

2020-05-25 16:54 UTC, JasonGross commented on src/CLI.v
> +          parse_args (args : list string)
There's a recent change I made that changed the format of `PipelineAPI` to make it a bit more structured, so you'll have to update this, sorry.  (Or I can suggest the appropriate change if you'd like, but I suspect it'll be pretty easy to copy from the word-by-word montgomery api).

2020-05-25 16:55 UTC, JasonGross commented on src/ExtractionHaskell/test.v
> +(* cat /tmp/test.hs.out | sed -f haskell.sed  > ../../test.hs *)
Was this leftover and you accidentally committed it?

2020-05-25 17:00 UTC, JasonGross commented on src/PushButtonSynthesis/WordByWordMontgomeryDivstepReificationCache.v
> +Require Import Lists.List.
Please move this higher up in the file, above the first definition

2020-05-25 17:00 UTC, JasonGross commented on src/PushButtonSynthesis/WordByWordMontgomeryDivstepReificationCache.v
> +Compute fold_right (fun a b => a - b) 1 []. Compute Z.log2 3.
These should be removed before we merge

2020-05-25 17:01 UTC, JasonGross commented on src/PushButtonSynthesis/WordByWordMontgomeryDivstepReificationCache.v
> +  end in res.
Does this belong here, or in some arithmetic file?

2020-05-26 20:02 UTC, bshvass commented
Hey @huitseeker! You are more than welcome to jump in if you have suggestions or improvements.

2020-06-02 11:46 UTC, bshvass commented on src/PushButtonSynthesis/WordByWordMontgomeryDivstep.v
> +             (forall a, valid a)).
Thanks for the offer. I am not sure how to get `strip_bounds_info` and `stringify_rec0` (from `Primitives.v` to recognise and properly convert the correctness properties to strings, so i would appreciate help with that. I have added the correctness properties to `COperationSpecifications` in the latest commit.

2020-06-03 18:26 UTC, JasonGross commented on src/COperationSpecifications.v
> +        valid v -> valid r ->
The correctness condition stringification does not support let-binders shared between preconditions and post conditions
```suggestion
      := forall (d : Z) f g v r,
        valid v -> valid r ->
         let '(d1,f1,g1,v1,r1) := divstep d f g v r in
```

2020-06-03 18:53 UTC, JasonGross commented on src/PushButtonSynthesis/WordByWordMontgomeryDivstep.v
> +             (forall a, valid a)).
If you rebase this PR on top of #810 (which I'll be merging into master as soon as the CI passes on it) and commit the suggestion I make in https://github.com/mit-plv/fiat-crypto/pull/670/files#r434769186 , then the stringification routine should work for all three definitions you add.

2020-06-03 18:54 UTC, JasonGross commented
Please rebase this on the tip of master, to get rid of the conflicts, if that's not too much toruble (I generally perfer merging PRs by rebasing them rather than with a merge commit). Btw, if you want to submit updates to the ZUtil files as a separate PR, I can merge those in now, so there's less rebuilding to be done when switching between this branch and master.

2020-08-11 14:22 UTC, bshvass commented
I believe all requests have been fixed. I don't know if you have time to review the PR, @JasonGross? Thanks.

2020-08-12 17:18 UTC, JasonGross commented
Thanks!  I'll make another pass through it, and hopefully this can be merged soon.

2020-08-12 18:04 UTC, jadephilipoom commented on src/COperationSpecifications.v
> +      := Eval cbv [divstep_spec_full] in
I'd prefer to remove the compute and simply repeat the definition of `divstep_spec_full`; this is what the other correctness definitions do, and makes the definition more readable.

2020-08-12 18:20 UTC, jadephilipoom commented on src/COperationSpecifications.v
> +    Definition precomp_correct
The name "precomp" seems a little vague; if it doesn't have some other name we can use, maybe `divstep_precomp`?

2020-08-13 07:00 UTC, bshvass commented on src/Util/Notations.v
> +Reserved Infix "|'" (at level 50).
The one in line 78 is a different character (∣ vs |). There is also an earlier comment on this, where Jason suggested just removing the one in line 78.

2020-08-13 07:05 UTC, bshvass commented on src/Util/ZUtil/Pow.v
> +  (* faster modular exponentation for computing (not sure where to put this) *)
There is a `+ 1` making it `(a - 1) * 1 + 1 = a` when the bit is in `1` and `(a - 1) * 0 + 1 = 1` if the bit is `0`. I can add this as a comment.

2020-08-13 07:16 UTC, bshvass commented on src/PushButtonSynthesis/InversionReificationCache.v
> +  let precomp := (Z.sq_and_multiply_mod k i m) in
I tried using `Z.pow` followed by `Z.modulo`, but the computation hang (presumably because the exponentiation gets too large, the base is of size ~p/2 and the exponent of size ~3 * log p). Using this instead fixed the issue. Now that I think about it though, we could probably just use a simpler power function which reduced after every multiplication (instead of doing the multiplications first).

2020-08-13 15:45 UTC, spitters commented
@jadephilipoom 
> Not a blocker for merging, but would it be feasible to create a Coq version of the full inversion algorithm (with loop, as in the C code) and prove it correct?

I thought loops were not supported yet?

2020-08-13 15:59 UTC, bshvass commented
> @jadephilipoom
> 
> > Not a blocker for merging, but would it be feasible to create a Coq version of the full inversion algorithm (with loop, as in the C code) and prove it correct?
> 
> I thought loops were not supported yet?

You could still prove a Coq version correct, just not one that is reifiable in fiat.

2020-08-13 16:06 UTC, bshvass commented
@jadephilipoom 
> It seemed like this was closer to merging, so I looked over it again. Thanks for the hard work!
>
Thanks for the comments. 
> Not a blocker for merging, but would it be feasible to create a Coq version of the full inversion algorithm (with loop, as in the C code) and prove it correct?

The paper-proof is, unfortunately, not too easy to formalize, but I am currently working on it. I think it is feasible, but it will probably rely on some axioms which fiat does not. 

> 
> I have a naming nitpick also; this algorithm is just called "inversion" in file names (e.g. `Arithmetic/Inv.v`, `PushButtonSynthesis/InversionReificationCache.v`), but the fiat-crypto repo also contains inversion by Fermat's little theorem, and there's some active work that will likely add more FLT-inversion code. So I think it might be a good idea to be specific here. Maybe BY for Bernstein-Yang, as in `BYInv.v` and `BYInversionReificationCache.v`?

I agree and will fix this.

2020-08-13 16:36 UTC, jadephilipoom commented on src/Util/ZUtil/Pow.v
> +  (* faster modular exponentation for computing (not sure where to put this) *)
Ah, I see, I eyeballed the parentheses wrong -- that's fine then.

2020-08-13 16:36 UTC, jadephilipoom commented on src/PushButtonSynthesis/InversionReificationCache.v
> +  let precomp := (Z.sq_and_multiply_mod k i m) in
Okay, I see why it was needed. But it would be nice to avoid adding new code just for the precomputed value (and avoid creating a new top-level synthesized operation just for computing a constant).

What about following the model we used for the modular inverse in Montgomery multiplication: that is, take in the precomputed value as an argument/context variable, and require as a precondition that it has the arithmetically correct value? Then the caller can compute it however they want. You can add the square-and-multiply definition to its own ZUtil file (maybe renaming it something like `modexp` to make it clear that this is modular exponentiation, and not tie the name to the implementation), like we've done with modular inverse (`modinv`), and use that to compute the argument in the PushButtonSynthesis file.

See:
https://github.com/mit-plv/fiat-crypto/blob/9f08fb67c944da8d30673c28f027726faaa1db78/src/PushButtonSynthesis/WordByWordMontgomery.v#L117
 https://github.com/mit-plv/fiat-crypto/blob/9f08fb67c944da8d30673c28f027726faaa1db78/src/PushButtonSynthesis/WordByWordMontgomery.v#L166

2020-08-13 16:37 UTC, jadephilipoom commented
> You could still prove a Coq version correct, just not one that is reifiable in fiat.

Yep, this is what I meant. The background is that although loops are *currently* not supported, there's some work in that direction and it would be cool to have the proofs in place when we're ready for them.

2020-08-13 17:23 UTC, spitters commented
@jadephilipoom yes, that proof would be interesting, but is rather long, and it should probably not stall this PR.

2020-08-13 17:26 UTC, jadephilipoom commented
> @jadephilipoom yes, that proof would be interesting, but is rather long, and it should probably not stall this PR

Agreed; as I said, not a blocker for merging this

2020-08-24 00:05 UTC, bshvass commented on src/PushButtonSynthesis/InversionReificationCache.v
> +  let precomp := (Z.sq_and_multiply_mod k i m) in
I see the idea and have fixed it now. I have however not added a check, since I'm not sure exactly what equation you could verify. You could check that `modexp a b m = a ^ b mod m`, but this would again be slow.

2020-08-27 04:01 UTC, JasonGross commented on src/Util/ZUtil/OnesFrom.v
> +  Proof. unfold Z.ones_from; solve_testbit. Qed.
This isn't quite `full`.  Could you write a version that has `if 0 <=? k then ... else ...`?  (Note that `Z.ones x = -1` for `x < 0`, which you can prove via `Z.ones_equiv`.  And `Z.testbit (-1) i = true` for non-negative `i`.)

2020-08-27 04:01 UTC, JasonGross commented on src/Util/ZUtil/Pow.v
> +Require Import Lists.List.
```suggestion
Require Import Coq.Lists.List.
```

2020-08-27 04:21 UTC, JasonGross commented on src/Util/ZUtil/ModExp.v
> +    unfold modexp; destruct p; simpl; rewrite modexp_nat_correct, ?Zpower_pos_nat by assumption; first [reflexivity|lia]. Qed.
Here is a version that is asymptotically more efficient for large exponents, and a bit simpler, based on the definition of `Z.pow`:
```suggestion
Local Open Scope Z_scope.

Module Z.
  Definition modexp_pos a p m := Pos.iter (fun z => (a * z) mod m) (1 mod m) p.
  Definition modexp a p m
    := match p with
       | 0 => 1 mod m
       | Z.neg _ => 0
       | Z.pos p => modexp_pos a p m
       end.

  Lemma modexp_pos_correct a p m
    : modexp_pos a p m = Z.pow_pos a p mod m.
  Proof.
    cbv [Z.pow_pos modexp_pos].
    erewrite Pos.iter_swap_gen with (f := fun a => a mod m).
    { reflexivity. }
    { cbv beta; intros; now rewrite Zmult_mod_idemp_r. }
  Qed.

  Lemma modexp_correct a p m
    : modexp a p m = a ^ p mod m.
  Proof.
    cbv [modexp Z.pow]; destruct p;
      now rewrite ?modexp_pos_correct, ?Zmod_0_l.
  Qed.
```

2020-08-27 04:26 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveRange.v
> +                               end
We have a tactic that does this:
```coq
Require Import Crypto.Util.Tactics.UniquePose.
```
and then you can just do
```suggestion
    | [ |- context[?a ^ ?b] ] => unique assert (0 <= a ^ b) by (apply Z.pow_nonneg; lia)
```

2020-08-27 04:27 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveRange.v
> +    | [ |- 0 < _ ^ _ ] => apply Z.pow_pos_nonneg
Maybe add the `Z.truncating_shiftl` case to `Z.zero_bounds` and then you can
```suggestion
    | _ => progress Z.zero_bounds
```
if you `Require Import Crypto.Util.ZUtil.Tactics.ZeroBounds`

2020-08-27 04:29 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +       symmetry; apply Z.land_ones; lia. Qed.
Please move this to `Testbit.v` and make it non-local

2020-08-27 04:29 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +  rewrite Z.bits_above_log2; simpl; try reflexivity; lia. Qed.
Please move this to `Testbit.v` and make it non-local

2020-08-27 04:30 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +          end; simpl; subst);
Please don't `simpl` here.  Instead use `cbn [<some explicit list of things you want to unfold>]`.  Tactics with `simpl` in them tend to not scale very well.

2020-08-27 04:31 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +          | [ |- _ <= _ < _] => auto with zarith
```suggestion
          | [ |- _ <= _ < _] => solve [ auto with zarith ]
```
otherwise if you add something below this case it'll never trigger

2020-08-27 04:31 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +          | [ |- _ ] => progress autorewrite with testbit_pos_rewrite
```suggestion
          | _ => progress autorewrite with testbit_pos_rewrite
```

2020-08-27 04:33 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +  - apply Z.pow2_bits_false; lia. Qed.
All of these belong as non-local lemmas in Testbit.v, I believe

2020-08-27 04:34 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +          end; simpl; subst);
Same comment about not using `simpl`, but using `cbn` with a whitelist instead

2020-08-27 04:34 UTC, JasonGross commented on src/Util/ZUtil/Tactics/SolveTestbit.v
> +          | [ |- _ <= _ < _] => auto with zarith
```suggestion
          | [ |- _ <= _ < _] => solve [ auto with zarith ]
```

2020-09-07 13:02 UTC, bshvass commented on src/PushButtonSynthesis/WordByWordMontgomeryReificationCache.v
> +    (* Time cache_reify_faster_1arg ().  *)
I do need 1 in the montgomery domain, if that is what you mean? If you use cache_reify_faster_1arg, then compilation breaks (at least on my machine)

2020-09-07 13:03 UTC, bshvass commented on src/Util/ZUtil/ModExp.v
> +    unfold modexp; destruct p; simpl; rewrite modexp_nat_correct, ?Zpower_pos_nat by assumption; first [reflexivity|lia]. Qed.
Thanks for the suggestion!

2020-09-07 13:06 UTC, bshvass commented
Thanks for the review @JasonGross! I believe I have addressed all suggestions in my latest commit.

2020-09-07 17:31 UTC, JasonGross commented on src/PushButtonSynthesis/WordByWordMontgomeryReificationCache.v
> +    (* Time cache_reify_faster_1arg ().  *)
It seemed to me like you were changing from `cache_reify_faster_1arg` to `cache_reify` on a definition that already existed and worked fine with `cache_reify_faster_1arg`.  I'm aware that this tactic does indeed cause compilation failures in some cases, but I'm a bit confused by a compilation failure suddenly showing up in an unchanged definition, and am wondering what I'm missing.

2020-09-08 08:11 UTC, bshvass commented on src/PushButtonSynthesis/WordByWordMontgomeryReificationCache.v
> +    (* Time cache_reify_faster_1arg ().  *)
Ah, I believe it worked previously since `["one", sone]` wasn't in `known_functions`
https://github.com/mit-plv/fiat-crypto/blob/6ef489d015c527a7504b9e6aac961fbdd1f80260/src/PushButtonSynthesis/WordByWordMontgomery.v#L903-L914
That is, both having `sone` as a known function and using `cache_reify_faster_1arg` breaks compilation

2020-09-15 16:07 UTC, JasonGross requested changes
Sorry again for the delay (thesis writing is taking much of my time and energy), and thanks for bearing with me.  Assuming all changes were addressed, this looks good to me once the CI passes.  The current issues are:
1. `fiat_p256_one` is a name conflict with a BoringSSL symbol; I'd suggest just using the constant inline wherever you need it, or else renaming it (e.g., to `set_one` or `assign_one` or similar)
The error is
> `../crypto/fipsmodule/ec/p256.c:50:30: error: ‘fiat_p256_one’ redeclared as different kind of symbol
> static const fiat_p256_felem fiat_p256_one = {0x1, 0xffffffff00000000,
Alternatively, we can ask @davidben if a definition like
```c
static void fiat_p256_one(uint64_t out1[4]) {
  out1[0] = 0x1;
  out1[1] = UINT64_C(0xffffffff00000000);
  out1[2] = UINT64_C(0xffffffffffffffff);
  out1[3] = UINT32_C(0xfffffffe);
}
```
is enough for BoringSSL, or how to make the files play nicely together.  (My inclination, though, is to just rename it.)
2. It looks like you forgot to regenerate the Go, Java, JSON, and Rust files (just run `make` and it'll build them all)

2020-09-15 16:07 UTC, JasonGross commented on inversion-c/p224_32.c
> +}
Why not factor this out into an `inversion_template.c` file which you can then include into all of these C files so that you don't need to duplicate the code?  (Not necessary for merging this PR, though.)  And similarly for the test files.

2020-09-15 16:07 UTC, JasonGross commented on src/Util/ZUtil/Definitions.v
> +    (if ((a mod 2 ^ m) <? 2 ^ (m - 1)) then a mod 2 ^ m else a mod 2 ^ m - 2 ^ m).
Would you be willing to merge this comment, so that we have a record of this?

2020-10-13 11:49 UTC, bshvass commented
I am encountering a problem with synthesis of bedrock2-code (all other languages seem to synthesize). I get the error 

`Error occured during translation to bedrock2. This is likely because a part of the input expression either had unsupported integer types (bedrock2 requires that all integers have the same size) or contained an unsupported operation.`

How exactly is this to be interpreted? Does it mean that you cannot have functions that take a word-sized integer and a multi-limb-sized integer and return a pair of such? Or simply that all integer-types must be the same.

I tried simplifying the function (`divstep`) to simply be the identity, but the issue persists. I have included the generated .tmp-file below.

```
check_args
/* Autogenerated: src/ExtractionOCaml/bedrock2_word_by_word_montgomery --lang bedrock2 --static --no-wide-int --widen-carry --widen-bytes --split-multiret --no-select p256 64 '2^256 - 2^224 + 2^192 + 2^96 - 1' mul square add sub opp from_montgomery to_montgomery nonzero selectznz to_bytes from_bytes one msat divstep divstep_precomp */
/* curve description: p256 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: mul, square, add, sub, opp, from_montgomery, to_montgomery, nonzero, selectznz, to_bytes, from_bytes, one, msat, divstep, divstep_precomp */
/* m = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff (from "2^256 - 2^224 + 2^192 + 2^96 - 1") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/* eval z = z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) */
/* bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) */

#include <stdint.h>
#include <memory.h>

// LITTLE-ENDIAN memory access is REQUIRED
// the following two functions are required to work around -fstrict-aliasing
static inline uintptr_t _br2_load(uintptr_t a, size_t sz) {
  uintptr_t r = 0;
  memcpy(&r, (void*)a, sz);
  return r;
}

static inline void _br2_store(uintptr_t a, uintptr_t v, size_t sz) {
  memcpy((void*)a, &v, sz);
}




In fiat_p256_divstep:
Stringification failed on the syntax tree:
(λ x1 x2 x3 x4 x5,
  expr_let x6 := x2[0] (* : uint64_t *) in
  expr_let x7 := x2[1] (* : uint64_t *) in
  expr_let x8 := x2[2] (* : uint64_t *) in
  expr_let x9 := x2[3] (* : uint64_t *) in
  expr_let x10 := x2[4] (* : uint64_t *) in
  expr_let x11 := x3[0] (* : uint64_t *) in
  expr_let x12 := x3[1] (* : uint64_t *) in
  expr_let x13 := x3[2] (* : uint64_t *) in
  expr_let x14 := x3[3] (* : uint64_t *) in
  expr_let x15 := x3[4] (* : uint64_t *) in
  expr_let x16 := x4[0] (* : uint64_t *) in
  expr_let x17 := x4[1] (* : uint64_t *) in
  expr_let x18 := x4[2] (* : uint64_t *) in
  expr_let x19 := x4[3] (* : uint64_t *) in
  expr_let x20 := x5[0] (* : uint64_t *) in
  expr_let x21 := x5[1] (* : uint64_t *) in
  expr_let x22 := x5[2] (* : uint64_t *) in
  expr_let x23 := x5[3] (* : uint64_t *) in
  ((uint64_t, ??, ??, ??)((uint64_t, ??, ??)((uint64_t, ??)((uint64_t)x1, (uint64_t)x6 :: (uint64_t)x7 :: (uint64_t)x8 :: (uint64_t)x9 :: (uint64_t)x10 :: []), (uint64_t)x11 :: (uint64_t)x12 :: (uint64_t)x13 :: (uint64_t)x14 :: (uint64_t)x15 :: []), (uint64_t)x16 :: (uint64_t)x17 :: (uint64_t)x18 :: (uint64_t)x19 :: []), (uint64_t)x20 :: (uint64_t)x21 :: (uint64_t)x22 :: (uint64_t)x23 :: [])
)
ERROR-CONTAINING OUTPUT:
/*
 * Input Bounds:
 *   in0: [0x0 ~> 0xffffffffffffffff]
 *   in1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   in2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   in3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   in4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out0: [0x0 ~> 0xffffffffffffffff]
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
uintptr_t internal_fiat_p256_divstep(uintptr_t out1, uintptr_t out2, uintptr_t out3, uintptr_t out4, uintptr_t in0, uintptr_t in1, uintptr_t in2, uintptr_t in3, uintptr_t in4) {
  uintptr_t x18, x0, x19, x1, x20, x2, x21, x3, x22, x4, x23, x5, x24, x6, x25, x7, x26, x8, x27, x9, x28, x10, x29, x11, x30, x12, x31, x13, x32, x14, x33, x15, x34, x16, x35, x17, ERROR, out0, x36, x37, x38, x39, x40;
  /*skip*/
  x0 = _br2_load((in1)+((uintptr_t)0ULL), sizeof(uintptr_t));
  x1 = _br2_load((in1)+((uintptr_t)8ULL), sizeof(uintptr_t));
  x2 = _br2_load((in1)+((uintptr_t)16ULL), sizeof(uintptr_t));
  x3 = _br2_load((in1)+((uintptr_t)24ULL), sizeof(uintptr_t));
  x4 = _br2_load((in1)+((uintptr_t)32ULL), sizeof(uintptr_t));
  /*skip*/
  x5 = _br2_load((in2)+((uintptr_t)0ULL), sizeof(uintptr_t));
  x6 = _br2_load((in2)+((uintptr_t)8ULL), sizeof(uintptr_t));
  x7 = _br2_load((in2)+((uintptr_t)16ULL), sizeof(uintptr_t));
  x8 = _br2_load((in2)+((uintptr_t)24ULL), sizeof(uintptr_t));
  x9 = _br2_load((in2)+((uintptr_t)32ULL), sizeof(uintptr_t));
  /*skip*/
  x10 = _br2_load((in3)+((uintptr_t)0ULL), sizeof(uintptr_t));
  x11 = _br2_load((in3)+((uintptr_t)8ULL), sizeof(uintptr_t));
  x12 = _br2_load((in3)+((uintptr_t)16ULL), sizeof(uintptr_t));
  x13 = _br2_load((in3)+((uintptr_t)24ULL), sizeof(uintptr_t));
  /*skip*/
  x14 = _br2_load((in4)+((uintptr_t)0ULL), sizeof(uintptr_t));
  x15 = _br2_load((in4)+((uintptr_t)8ULL), sizeof(uintptr_t));
  x16 = _br2_load((in4)+((uintptr_t)16ULL), sizeof(uintptr_t));
  x17 = _br2_load((in4)+((uintptr_t)24ULL), sizeof(uintptr_t));
  /*skip*/
  /*skip*/
  x18 = x0;
  x19 = x1;
  x20 = x2;
  x21 = x3;
  x22 = x4;
  x23 = x5;
  x24 = x6;
  x25 = x7;
  x26 = x8;
  x27 = x9;
  x28 = x10;
  x29 = x11;
  x30 = x12;
  x31 = x13;
  x32 = x14;
  x33 = x15;
  x34 = x16;
  x35 = x17;
  x36 = ERROR;
  x37 = ERROR;
  /*skip*/
  x38 = ERROR;
  /*skip*/
  x39 = ERROR;
  /*skip*/
  x40 = ERROR;
  /*skip*/
  out0 = x36;
  _br2_store((out1)+((uintptr_t)0ULL), x37, sizeof(uintptr_t));
  /*skip*/
  _br2_store((out2)+((uintptr_t)0ULL), x38, sizeof(uintptr_t));
  /*skip*/
  _br2_store((out3)+((uintptr_t)0ULL), x39, sizeof(uintptr_t));
  /*skip*/
  _br2_store((out4)+((uintptr_t)0ULL), x40, sizeof(uintptr_t));
  /*skip*/
  return out0;
}


Error occured during translation to bedrock2. This is likely because a part of the input expression either had unsupported integer types (bedrock2 requires that all integers have the same size) or contained an unsupporte [...]

2020-10-14 19:26 UTC, JasonGross commented
This is a question for @jadephilipoom , but my current guess is that the bedrock2 output doesn't support functions that return multiple arrays/lists.  @jadephilipoom can you confirm?

I'd be fine with adjusting the Makefile to simply not generate divstep for the bedrock2 output, while we're working on getting it supported, so we can merge this sooner.  If you want help with doing this, let me know (I expect it's about a 5--10 minute project for me to adjust the Makefile.)

2020-10-14 19:41 UTC, jadephilipoom commented
> This is a question for @jadephilipoom , but my current guess is that the bedrock2 output doesn't support functions that return multiple arrays/lists. @jadephilipoom can you confirm?

No, it should support multiple arrays in the return values. Although it wouldn't shock me if there were errors, since none of the other operations test that functionality. If it's changed from `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => (x1, x2, x3, x4, x5)` to `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => x1`, does the issue persist?

2020-10-15 10:29 UTC, bshvass commented
@jadephilipoom Both `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => x1` and `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => x2` synthesize correctly, but `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => (x1, x2)` and `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => (x2, x3)` both fail. On the other hand `fun (x1 x2 : Z) (x3 .. : listZ) => (x1, x2)` also does not synthesize correctly, which doesn't really agree with the fact that addcarryx and mulx synthesizes properly?
@JasonGross It should be disabled in my latest commit.

2020-10-27 15:26 UTC, JasonGross approved these changes
Sorry, I just saw your updates now.  Thanks for doing all this working, and bearing with us through the long review process!

2020-10-27 15:27 UTC, merged